version: "2"

services:
  rng_win:
    build: rng_win
    ports:
    - "8001:80"

  hasher_win:
    build: hasher_win
    ports:
    - "8002:80"

  webui:
    build: webui
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    build: worker

